### PR TITLE
Fixes crash when using UIImage.scale_to with a background color

### PR DESCRIPTION
**Pull request by markrickert**
when not including sugarcube-color in the project.

### CODE REVIEW

**Comment by markrickert** [comment]
I've gotten around this temporarily in my app by defining:

```ruby
class UIColor
  def uicolor
    self
  end
end
```

**Comment by colinta** [comment]
No SPECS!?!?  Mark, where is your head at? :wink:

**Comment by colinta** [comment]
Available in 3.3.2.  Thanks as always!

**Comment by markrickert** [comment]
It would have been pretty hard to test since with sugarcube-colors required in the spec, it would behave as it should no matter what.

**Comment by colinta** [comment]
Haha I know it - all the more reason to give you sh*t about it! :-D

**Pull request merged**
