### PR TITLE
Adds convenience methods to NSDate for yesterday? and tomorrow?

### PR DESCRIPTION
**Pull request by markrickert**
With tests, of course :)

### CODE REVIEW

**Comment by colinta** [comment]
Nice dude!  Running the tests now (I dunno what's up w/ Travis atm)

**Comment by markrickert** [comment]
Some of the 64bit tests are failing because `NSIndexPath` is now returned as an `ImmediateRef`. Check out private rubymotion-alpha slack room for the chat with @lrz and @jamonholmgren earlier this morning.

**Comment by colinta** [comment]
Available in 3.0.6.  Thanks again!

**Comment by markrickert** [comment]
WOOHOO!

**Pull request merged**
