### PR TITLE
NSColor on 10.8

### PR DESCRIPTION
**Pull request by bmichotte**
```objective-c
+ (NSColor *)colorWithRed:(CGFloat)red green:(CGFloat)green blue:(CGFloat)blue alpha:(CGFloat)alpha
``` 

has been introduced on 10.9 

This PR add a test for NSColor responding to this method, otherwise call 

```objective-c
+ (NSColor *)colorWithCalibratedRed:(CGFloat)red green:(CGFloat)green blue:(CGFloat)blue alpha:(CGFloat)alpha
```

thanks

### CODE REVIEW

**Comment by colinta** [comment]
Nice, thanks for adding that check.

I wonder if we should add a centralized helper for that check... but I can't think of where.  Maybe a future refactor.

I'm down a rabbit hole at the moment, getting specs to run again for OS X.  They've been broken for a long time, and there are legitimate bugs!

**Comment by bmichotte** [comment]
I thought of adding something like ˋNSColor.rgba(r, g, b, a)ˋ and do the check in this method.
Can refactor it if you want

**Comment by bmichotte** [comment]
So ˋ does not work on iPhone ;)

**Comment by colinta** [comment]
Yeah let's do that, it'll be easier for people to use that code as an example in the future.

**Comment by bmichotte** [comment]
Here we go !

**Comment by colinta** [comment]
Nice!  I've got my spec fixes on another branch, merging next.

**Pull request merged**
