### PR TITLE
Adding support for UIScreenEdgePanGestureRecognizer via existing on_pan helper

### PR DESCRIPTION
**Pull request by dchersey**
I needed to use a pan gesture recognizer that only recognizes gestures from the edges. 
I thought it would be simples from an API perspective to add an :edges option to the existing on_pan method from gestures.  

If the edges option is present, and is anything other than [:none], we use the UIScreenEdgePanGestureRecognizer instead of the UIPanGestureRecognizer.  

It is not valid to specify fingers options or count for the edge recognizer in IOS so I ignore any of those options if specified along with :edges.

### CODE REVIEW

**Comment by colinta** [comment]
Looks good!  I like the `on_pan(edges: [])` syntax.  Can you just add some specs to `gestures_specs.rb` and `symbol_constants_specs.rb`, and maybe a note about usage in the README?

**Comment by dchersey** [comment]
Done!

**Comment by colinta** [comment]
I tested locally, and actually I did see some strange failures, they were all in date and location additions. So GTG!

**Comment by colinta** [comment]
Available in 3.4.0

**Comment by dchersey** [comment]
Yes, I saw those too ... I thought it was me :s

**Pull request merged**
