### PR TITLE
added CALayer#unshift

### PR DESCRIPTION
**Pull request by matsu911**

### CODE REVIEW

**Comment by colinta** [comment]
Could you throw in a quick spec for this?  Should be easy to test :smiley:

**Comment by matsu911** [comment]
added a spec

**Comment by colinta** [comment]
Awesome! Thanks.  I just noticed that this is forked off of an older version of SugarCube (pre 3.0).  Have you tried to merge it with a more recent version?

**Comment by colinta** [comment]
Nevermind, it merged with no problems.  Thanks!

**Pull request merged**
